---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | test | /etc/ssh/ssh_config'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | test | /etc/ssh/ssh_config'
        test_src: 'files/ssh_config'
        test_file: '/etc/ssh/ssh_config'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    # Values are internal values NOT ssh_config values; check exit code only.
    - name: 'Verify | cmd | query SSH configuration'
      ansible.builtin.command: 'ssh -G test'
      changed_when: false
      failed_when: false
      register: ssh__test_ssh_g_test

    - name: 'Verify | assert | SSH configuration no static errors'
      ansible.builtin.assert:
        quiet: true
        that:
          - ssh__test_ssh_g_test.rc == 255
          - ssh__test_ssh_g_test.stderr is match('^/etc/ssh/ssh_config line 26')  # yamllint disable-line rule:line-length
        fail_msg: >-
          ✘ 'ssh -G test' returned static errors:
          {{ ssh__test_ssh_g_test.stderr }}.
