---
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'
- name: 'Packages'
  ansible.builtin.include_tasks: 'packages.yml'
- name: 'SSHD config'
  ansible.builtin.include_tasks: 'sshd_config.yml'
- name: 'SSH config'
  ansible.builtin.include_tasks: 'ssh_config.yml'
- name: 'Host keys'
  ansible.builtin.include_tasks: 'host_keys.yml'
