---
###############################################################################
# Manage Files
###############################################################################
# Many SSH options may specify a file path or file contents.
#
# * If it is a file path; remove the managed file
# * If it is contents; create a managed file
# * If empty, do nothing
#
# Args:
#   managed_file_name: str - name of variable.
#   managed_file_path: str - file path for managed file (if determined).
#   managed_file_contents: str - variable contents.
#   managed_file_owner: str - file owner. Default: 'root'.
#   managed_file_group: str - file group. Default: 'root'.
#   managed_file_mode: str - octal file mode. Default: '0644'.

- name: 'Manage file | manage {{ managed_file_name }}'
  when: managed_file_contents | length > 0
  block:
    - name: 'Manage file | query {{ managed_file_name }}'
      ansible.builtin.stat:
        path: '{{ managed_file_contents }}'
      changed_when: false
      failed_when: false
      register: _ssh_server_manage_file

    - name: 'Manage file | generate {{ managed_file_path }}'
      ansible.builtin.copy:
        dest: '{{ managed_file_path }}'
        content: '{{ managed_file_contents }}'
        owner: '{{ managed_file_owner | default("root") }}'
        group: '{{ managed_file_group | default("root") }}'
        mode: '{{ managed_file_mode | default("0644") }}'
      when: not _ssh_server_manage_file.stat.exists

    - name: 'Manage file | remove {{ managed_file_path }}'
      ansible.builtin.file:
        path: '{{ managed_file_path }}'
        state: 'absent'
      when: _ssh_server_manage_file.stat.exists
