---
# yamllint disable rule:line-length
collections:
  - name: 'community.crypto'  # https://docs.ansible.com/ansible/latest/collections/community/crypto/

roles:
  - name: 'r_pufky.srv.apt'  # https://github.com/r-pufky/ansible_collection_srv
