---
# yamllint disable rule:line-length
###############################################################################
# Prepare
###############################################################################
# Manually generate testing certificate authority and sign keys for
# HostCertificate option testing.
#
# Reference:
# * https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Certificate-based_Authentication
# yamllint enable rule:line-length

- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | packages to generate testing keys'
      ansible.builtin.apt:
        name:
          - 'openssh-client'  # required for ssh-keygen
          - 'openssh-server'  # required for pre-existing host keys
        update_cache: true
        state: 'present'

    - name: 'Prepare | create /run/sshd for testing SSHD (sshd -T)'
      ansible.builtin.file:
        path: '/run/sshd'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'

    - name: 'Prepare | generate testing host key'
      ansible.builtin.command:
        argv:
          - 'ssh-keygen'
          - '-t'
          - 'rsa'
          - '-b'
          - '4096'
          - '-f'
          - '/tmp/ssh_host_rsa_key'
          - '-C'
          - ''
          - '-N'
          - ''
        creates: '/tmp/ssh_host_rsa_key'  # and ssh_host_rsa_key.pub.

    - name: 'Prepare | generate testing CA'
      ansible.builtin.command:
        argv:
          - 'ssh-keygen'
          - '-t'
          - 'ecdsa'
          - '-f'
          - '/tmp/ssh_host_ca_key'
          - '-C'
          - 'Host Certificate Authority for *.example.com'
          - '-N'
          - ''
        creates: '/tmp/ssh_host_ca_key'

    - name: 'Prepare | sign testing host key with testing CA'
      ansible.builtin.command:
        argv:
          - 'ssh-keygen'
          - '-h'
          - '-s'
          - '/tmp/ssh_host_ca_key'
          - '-V'
          - '+1d'
          - '-I'
          - 'abcd'
          - '-z'
          - '00001'
          - '-n'
          - 'server.example.com'
          - '/tmp/ssh_host_rsa_key'
        creates: '/tmp/ssh_host_rsa_key-cert.pub'
