---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | /etc/ssh/sshd_config'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | /etc/ssh/sshd_config'
        test_src: 'files/sshd_config'
        test_file: '/etc/ssh/sshd_config'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    # Values are internal values NOT ssh_config values; check exit code only.
    - name: 'Verify | test SSH configuration for static errors'
      ansible.builtin.command: 'sshd -T'  # requires /run/sshd to exist.
      changed_when: false
      failed_when: false
      register: _test_ssh_sshd_t_test

    - name: 'Verify | assert no static errors'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_ssh_sshd_t_test.rc == 0
        fail_msg: >
          ✘ 'sshd -T' returned static errors:
          {{ _test_ssh_sshd_t_test.stderr }}.

    - name: 'Verify | absent'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | absent | /etc/ssh/{{ item }}'
        test_file: '/etc/ssh/{{ item }}'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
        test_diff: true
      loop:
        - 'ssh_server_banner'
        - 'ssh_server_host_certificate'
        - 'ssh_server_host_key'
        - 'ssh_server_trusted_user_ca_keys'
