---
###############################################################################
# SSHD Handlers
###############################################################################

- name: 'Handlers | restart SSH'
  ansible.builtin.systemd:
    name: 'ssh'
    state: 'restarted'
    enabled: true
