---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | filesystem | query /tmp/ssh_host_rsa_key'
      ansible.builtin.slurp:
        src: '/tmp/ssh_host_rsa_key'
      register: ssh__test_host_key

    - name: 'Converge | filesystem | query /tmp/ssh_host_rsa_key.pub'
      ansible.builtin.slurp:
        path: '/tmp/ssh_host_rsa_key.pub'
      register: ssh__test_host_key_pub

    - name: 'Converge | filesystem | query testing trusted user key'
      ansible.builtin.slurp:
        src: '/tmp/ssh_host_rsa_key-cert.pub'
      register: ssh__test_trusted_user_key

    - name: 'Converge | role | r_pufky.deb.ssh'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.ssh'
      vars:
        ssh_cfg_server_host_certificate: >-
          {{ ssh__test_host_key_pub.content | b64decode }}
        ssh_cfg_server_host_key: '{{ ssh__test_host_key.content | b64decode }}'
        ssh_cfg_server_trusted_user_ca_keys: >-
          {{ ssh__test_trusted_user_key.content | b64decode }}
