---
# yamllint disable rule:line-length
- name: 'SSHD config all values | verify | sshd_config'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'SSHD config all values | verify | sshd_config | query global expected config'
      ansible.builtin.copy:
        src: 'files/sshd_config'
        dest: '/etc/ssh/sshd_config'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_ssh_sshd_config

    - name: 'SSHD config all values | verify | sshd_config | assert global config'
      ansible.builtin.assert:
        that:
          - not _test_ssh_sshd_config.changed
        fail_msg: '/etc/ssh/sshd_config is not in expected format: {{ _test_ssh_sshd_config.diff }}.'

- name: 'SSHD config all values | verify | sshd local configs'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'SSHD config all values | verify | sshd local configs | query local expected config'
      ansible.builtin.copy:
        src: 'files/local_config'
        dest: '/etc/ssh/sshd_config.d/test_config.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_ssh_sshd_local_config

    - name: 'SSHD config all values | verify | sshd local configs | assert local config'
      ansible.builtin.assert:
        that:
          - not _test_ssh_sshd_local_config.changed
        fail_msg: '/etc/ssh/sshd_config.d/test_config.conf is not in expected format: {{ _test_ssh_sshd_local_config.diff }}.'

- name: 'SSHD config all values | verify | no static errors'
  hosts: 'all'
  gather_facts: false
  tasks:
    # values are internal values NOT ssh_config values; check exit code only.
    - name: 'SSHD config all values | verify | no static errors | test ssh configuration for static errors'
      ansible.builtin.command: 'sshd -T'  # requires /run/sshd to exist.
      changed_when: false
      failed_when: false
      register: _test_ssh_sshd_t_test

    - name: 'SSHD config all values | verify | no static errors | assert no static errors'
      ansible.builtin.assert:
        that:
          - _test_ssh_sshd_t_test.rc == 0
        fail_msg: "'sshd -T' returned static errors: {{ _test_ssh_sshd_t_test.stderr }}."
