---
- name: 'SSHD config all values | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'SSH config all values | verify | /etc/ssh/sshd_config'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          'SSH config all values | verify | /etc/ssh/sshd_config'
        test_src: 'files/sshd_config'
        test_file: '/etc/ssh/sshd_config'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'

    - name: >
        SSH config all values | verify |
        /etc/ssh/sshd_config.d/test_config.conf
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: >
          SSH config all values | verify |
          /etc/ssh/sshd_config.d/test_config.conf
        test_src: 'files/local_config'
        test_file: '/etc/ssh/sshd_config.d/test_config.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'

    # Values are internal values NOT ssh_config values; check exit code only.
    - name: >
        SSHD config all values | verify |
        test SSH configuration for static errors
      ansible.builtin.command: 'sshd -T'  # requires /run/sshd to exist.
      changed_when: false
      failed_when: false
      register: _test_ssh_sshd_t_test

    - name: 'SSHD config all values | verify | assert no static errors'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_ssh_sshd_t_test.rc == 0
        fail_msg: >
          ✘ 'sshd -T' returned static errors:
          {{ _test_ssh_sshd_t_test.stderr }}.
