---
- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | create /run/sshd for verifying SSHD (sshd -T)'
      ansible.builtin.file:
        path: '/run/sshd'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'
