---
# yamllint disable rule:line-length
# Confirm default settings are set to expected values and config loads without
# error.
- name: 'Default | verify | ssh_config'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | ssh_config | query global expected config'
      ansible.builtin.copy:
        src: 'files/ssh_config'
        dest: '/etc/ssh/ssh_config'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_ssh_ssh_config

    - name: 'Default | verify | ssh_config | assert global config'
      ansible.builtin.assert:
        that:
          - not _test_ssh_ssh_config.changed
        fail_msg: '/etc/ssh/ssh_config is not in expected format: {{ _test_ssh_ssh_config.diff }}.'

    # values are internal values NOT ssh_config values; check exit code only.
    - name: 'Default | verify | ssh_config | test ssh configuration for static errors'
      ansible.builtin.command: 'ssh -G test'
      changed_when: false
      failed_when: false
      register: _test_ssh_ssh_g_test

    - name: 'Default | verify | ssh_config | assert no static errors'
      ansible.builtin.assert:
        that:
          - _test_ssh_ssh_g_test.rc == 0
        fail_msg: "'ssh -G test' returned static errors: {{ _test_ssh_ssh_g_test.stderr }}."

- name: 'Default | verify | sshd_config'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | sshd_config | query global expected config'
      ansible.builtin.copy:
        src: 'files/sshd_config'
        dest: '/etc/ssh/sshd_config'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_ssh_sshd_config

    - name: 'Default | verify | sshd_config | assert global config'
      ansible.builtin.assert:
        that:
          - not _test_ssh_sshd_config.changed
        fail_msg: '/etc/ssh/sshd_config is not in expected format: {{ _test_ssh_sshd_config.diff }}.'

    # values are internal values NOT ssh_config values; check exit code only.
    - name: 'Default | verify | sshd_config | test ssh configuration for static errors'
      ansible.builtin.command: 'sshd -T'  # requires /run/sshd to exist.
      changed_when: false
      failed_when: false
      register: _test_ssh_sshd_t_test

    - name: 'Default | verify | sshd_config | assert no static errors'
      ansible.builtin.assert:
        that:
          - _test_ssh_sshd_t_test.rc == 0
        fail_msg: "'sshd -T' returned static errors: {{ _test_ssh_sshd_t_test.stderr }}."

- name: 'Default | verify | RSA key management'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | RSA key management | query global expected config'
      ansible.builtin.stat:
        path: '/etc/ssh/ssh_host_dsa_key'
      register: _test_ssh_host_dsa_delete

    - name: 'Default | verify | RSA key management | query host RSA key strength'
      ansible.builtin.command: 'ssh-keygen -lf /etc/ssh/ssh_host_rsa_key'
      register: _test_ssh_rsa_host_key_strength
      changed_when: false
      failed_when: false

    - name: 'Default | verify | RSA key management | assert global config'
      ansible.builtin.assert:
        that:
          - not _test_ssh_host_dsa_delete.stat.exists
        fail_msg: '/etc/ssh/ssh_host_dsa_key should have been removed.'

    - name: 'Default | verify | RSA key management | assert correct RSA key strength'
      ansible.builtin.assert:
        that:
          - _test_ssh_rsa_host_key_strength.stdout.split(' ')[0] | int == 4096
        fail_msg: '/etc/ssh/ssh_host_rsa_key key strength should be {{ _test_ssh_rsa_host_key_strength.stdout.split(" ")[0] }} (expected: 4096).'
