---
# yamllint disable rule:line-length
# Install client and server for ssh-keygen, sshd -T testing
#
# Reference:
# * https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Certificate-based_Authentication
- name: 'SSHD managed files | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'SSHD managed files | prepare | base packages for bare-metal equivalency'
      ansible.builtin.apt:
        name:
          - 'openssh-client'  # required for ssh-keygen
          - 'openssh-server'  # required for pre-existing host keys
        update_cache: true
        state: 'present'

    - name: 'SSHD managed files | prepare | create /run/sshd for testing SSHD (sshd -T)'
      ansible.builtin.file:
        path: '/run/sshd'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'

    - name: 'SSHD managed files | prepare | create static banner file'
      ansible.builtin.copy:
        dest: '/etc/ssh/test_static_file_path'
        content: 'test login banner'
        owner: 'root'
        group: 'root'
        mode: '0644'
