---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | test | host and match mutually exclusive'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | test | host and match mutually exclusive'
        test_role: 'r_pufky.deb.ssh'
        test_fail_message:
          'ssh_cfg_client_match set did not trigger assertion.'
        ssh_cfg_client_host: ['*']
        ssh_cfg_client_match: {test: '*'}

    - name: 'Converge | test | kerberos AFS token not used'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | test | kerberos AFS token not used'
        test_role: 'r_pufky.deb.ssh'
        test_fail_message: >-
          ssh_cfg_server_kerberos_get_afs_token=true
          did not trigger assertion.
        ssh_cfg_server_kerberos_get_afs_token: true

    - name: 'Converge | test | RSA required key strength only increased'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | test | RSA required key strength only increased'
        test_role: 'r_pufky.deb.ssh'
        test_fail_message:
          'ssh_cfg_client_required_rsa_size=96 did not trigger assertion.'
        ssh_cfg_client_required_rsa_size: 96

    - name: 'Converge | test | authorized keys command'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | test | authorized keys command'
        test_role: 'r_pufky.deb.ssh'
        test_fail_message: >-
          ssh_cfg_server_authorized_keys_command_user=""
          did not trigger assertion.
        ssh_cfg_server_authorized_keys_command: 'echo "hi"'
        ssh_cfg_server_authorized_keys_command_user: ''

    - name: 'Converge | test | authorized principals command'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | test | authorized principals command'
        test_role: 'r_pufky.deb.ssh'
        test_fail_message: >-
          ssh_cfg_server_authorized_principals_command_user="" did not trigger
          assertion.
        ssh_cfg_server_authorized_principals_command: 'echo "hi"'
        ssh_cfg_server_authorized_principals_command_user: ''
