---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | /etc/ssh/ssh_config'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          'Verify | /etc/ssh/ssh_config'
        test_src: 'files/ssh_config'
        test_file: '/etc/ssh/ssh_config'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    - name: 'Verify | /etc/ssh/ssh_config.d/test_config.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | /etc/ssh/ssh_config.d/test_config.conf'
        test_src: 'files/local_config'
        test_file: '/etc/ssh/ssh_config.d/test_config.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    # Values are internal values NOT ssh_config values; check exit code only.
    - name: 'Verify | test SSH configuration for static errors'
      ansible.builtin.command: 'ssh -G test'
      changed_when: false
      failed_when: false
      register: _test_ssh_ssh_g_test

    - name: 'Verify | assert no static errors'
      ansible.builtin.assert:
        that:
          - _test_ssh_ssh_g_test.rc == 0
        fail_msg: >
          ✘ 'ssh -G test' returned static errors:
          {{ _test_ssh_ssh_g_test.stderr }}.*
